//! The storage abstraction. Backends (local FS now, S3 later) implement [`Store`];
//! the [`Manifest`] is the cheap, derived index that keeps recall from scanning every
//! object — it is always reconstructable from the records and is never authoritative.

use serde::{Deserialize, Serialize};

use crate::error::Result;
use crate::record::{MemoryType, Record};

/// A pluggable memory backend. A bundle is identified by a namespace; the same trait is
/// meant to be implemented by a future S3 backend without touching callers.
pub trait Store {
    /// Write (create or overwrite) a record, then refresh the derived index.
    fn put(&self, record: &Record) -> Result<()>;

    /// Fetch a record by id. Returns [`Error::NotFound`](crate::Error::NotFound) if absent.
    fn get(&self, id: &str) -> Result<Record>;

    /// List record ids in the bundle, sorted.
    fn list(&self) -> Result<Vec<String>>;

    /// Delete a record by id, then refresh the derived index.
    fn delete(&self, id: &str) -> Result<()>;

    /// Build the manifest digest of the bundle's frontmatter.
    fn manifest(&self) -> Result<Manifest>;
}

/// One manifest row: the frontmatter fields cheap enough to filter on before touching bodies.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManifestEntry {
    pub id: String,
    #[serde(rename = "type")]
    pub kind: MemoryType,
    pub description: String,
    #[serde(default)]
    pub tags: Vec<String>,
    pub updated: String,
    /// Bundle-relative object key, e.g. `memories/<id>.md`.
    pub key: String,
}

impl ManifestEntry {
    pub fn from_record(record: &Record) -> Self {
        let m = &record.meta;
        ManifestEntry {
            id: m.id.clone(),
            kind: m.kind,
            description: m.description.clone(),
            tags: m.tags.clone(),
            updated: m.updated.clone(),
            key: format!("memories/{}.md", m.id),
        }
    }
}

/// The machine-readable bundle index. Fetch it whole to pre-filter recall candidates.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Manifest {
    pub entries: Vec<ManifestEntry>,
}

impl Manifest {
    /// Render the human-facing `index.md` (the OKF navigation entrypoint).
    pub fn to_index_md(&self) -> String {
        let mut out =
            String::from("# Memory index\n\n_Auto-generated by s3mem — do not edit by hand._\n\n");
        if self.entries.is_empty() {
            out.push_str("_(empty)_\n");
            return out;
        }
        let mut sorted = self.entries.clone();
        sorted.sort_by(|a, b| a.id.cmp(&b.id));
        for e in &sorted {
            // Collapse control characters so a newline in `description` can't break out of
            // its list row and splice a raw line into the generated markdown.
            out.push_str(&format!(
                "- [`{}`]({}) — {} _({})_\n",
                one_line(&e.id),
                e.key,
                one_line(&e.description),
                e.kind
            ));
        }
        out.push_str(&format!("\n{} memories.\n", sorted.len()));
        out
    }
}

/// Replace control characters (newlines, tabs, …) with spaces so a value renders on a
/// single markdown line.
fn one_line(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect()
}
